FactoryBot.define do
    sequence :title do |n|
        "autoGeneratedTitle#{n}"
    end

    factory :task, class: Task do
        id
        title
        deadline{ Time.now + 1.hour }
        priority {0}
        state {0}
        memo {'sample memo'}
        association :category
        user_id {category.user_id}
    end
end