FactoryBot.define do
    sequence :name do |n|
        "autoGeneratedSampleName#{n}"
    end

    factory :user, class: User do
        id {Time.parse(Time.now).to_i}
        password {"autoGeneratedSamplePass"}
        name
    end
end