# For Github User
# github_username: "slack_member_id"

kmtym1998: "r.komatsuyama"
# github_username_B: "slack_member_id_B"
# github_username_C: "slack_member_id_C"
# abeyuya: "XXXXXXXXX"

# For Github Team
# github_teamname: "slack_member_id"

# github_teamname_A: "slack_member_id_D"
